env: dev3
server:
  port: 9001
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 94450
    url: jdbc:mysql://localhost:3306/order?characterEncoding=utf-8&useSSL=false
  application:
    name: order-server
mybatis:
  config-location: classpath:mybatis/mybatis-cfg.xml
  type-aliases-package: com.nysit.order.domain
  mapper-locations:
    - classpath:mybatis/mapper/*.xml
hystrix: 
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
